# -*- coding: utf-8 -*-
"""
MEGA BILIM — C QISM: BIOLOGIYA, HAYVONLAR, O'SIMLIKLAR, SOG'LIQ, OVQAT
"""

KNOWLEDGE = [
    # ---------- HAYVONLAR ----------
    ("sher", "Sher — «hayvonlar qiroli». Kuchli, jasur. Afrika savannalarida yashaydi."),
    ("yo'lbars", "Yo'lbars — yo'l-yo'l chiziqli yirik mushuk. Osiyo o'rmonlarida yashaydi."),
    ("bo'ri", "Bo'ri — bo'ron va o'rmonlarda yashaydigan yirtqich. Oqil va sodiq hayvon."),
    ("tulki", "Tulki — ayyor va chaqqon hayvon. To'q sariq dumi bilan mashhur."),
    ("ayiq", "Ayiq — katta va kuchli hayvon. Qishda uyqusiga kiradi."),
    ("quyon", "Quyon — uzun quloqli, tez yuguradigan kichik hayvon. Sabzini yaxshi ko'radi."),
    ("kiyik", "Kiyik — o'rmonlarda yashaydigan go'zal, tez yuguradigan hayvon. Shoxlari bor."),
    ("sug'ur", "Sug'ur — dashtda yashaydigan kemiruvchi. Chuqur in qazib yashaydi."),
    ("kirpi", "Kirpi — tikangan kichik hayvon. Xavf sezganda dumaloq bo'lib olishadi."),
    ("sichqon", "Sichqon — kichkina kemiruvchi. Filmlarda multfilm qahramoni sifatida mashhur!"),
    ("kalamush", "Kalamush — aqlli kemiruvchi. Laboratoriyalarda o'rganiladi."),
    ("yara", "Yarasa — tunda uchadigan sutemizuvchi. Ekolokatsiya bilan yo'l topadi."),
    ("delfin", "Delfin — aqlli dengiz hayvoni. Odamlar bilan do'stlashib o'ynaydi."),
    ("kit", "Kit — eng katta hayvon. Uzunligi 30 metrgacha yetishi mumkin."),
    ("akula", "Akula — dengizdagi yirtqich baliq. Film qahramoni sifatida ham mashhur."),
    ("sepiya", "Sekizoyoq (osminog) — 8 ta qo'li bo'lgan aqlli dengiz hayvoni. Rangini o'zgartira oladi."),
    ("meduza", "Meduza — shaffof, jelatinsimon dengiz hayvoni."),
    ("krab", "Qisqichbaqa — dengiz va qirg'oqda yashaydigan qattiq qurolli hayvon."),
    ("toshbaqa", "Toshbaqa — qobig'i bilan mashhur, juda uzoq yashaydigan hayvon."),
    ("ilon", "Ilon — oyoqsiz sudraluvchi. Ba'zilari zaharli bo'lishi mumkin."),
    ("kaltakesak", "Kaltakesak — to'rtta oyoqli mayda sudraluvchi. Issiq joylarda yashaydi."),
    ("timsoh", "Timsoh — suvda yashaydigan yirik yirtqich sudraluvchi."),
    ("qurbaqa", "Qurbaqa — suv va quruqlikda yashaydigan amfibiya. Voyaga yetishda metamorfoz o'tkazadi."),
    ("burgut", "Burgut — juda kuchli va uzoqni ko'radigan yirtqich qush."),
    ("lochin", "Lochin — tez uchadigan yirtqich qush."),
    ("boyo'g'li", "Boyo'g'li — tunda faol, aqlli qush. Boshini 270° ga bura oladi."),
    ("bulbul", "Bulbul — go'zal sayraydigan qush. Bahor qushlari orasida eng mashhuri."),
    ("to'ti", "To'ti — odam ovozini taqlid qila oladigan rang-barang qush."),
    ("pingvin", "Pingvin — ucha olmaydigan, lekin a'lo suzuvchi qush. Sovuq joylarda yashaydi."),
    ("tuyaqush", "Tuyaqush — dunyodagi eng katta qush. Yuguradi, uchmaydi."),
    ("tovuq", "Tovuq — xonaki qush. Tuxum va go'shti uchun boqiladi."),
    ("ot", "Ot — insonning eng sodiq yordamchilaridan biri. Poygada ham ishlatiladi."),
    ("sigir", "Sigir — sut beradigan xonaki hayvon. Sutdan pishloq, qaymoq tayyorlanadi."),
    ("qo'y", "Qo'y — juni va go'shti uchun boqiladigan xonaki hayvon."),
    ("echki", "Echki — chaqqon xonaki hayvon. Suti foydali."),
    ("tuya", "Tuya — cho'lda yashaydigan «sahro kemasi». Uzoq vaqt suvsiz yura oladi."),
    ("eshak", "Eshak — chidamli yuk tashuvchi hayvon."),
    ("it", "It — insonning eng sodiq do'sti. Qo'riqlash, ov va yordam uchun xizmat qiladi."),
    ("mushuk", "Mushuk — uy hayvoni. Silliq va chaqqon, sichqonlarni ovlaydi."),
    ("panda", "Panda — bambuk bilan oziqlanadigan ayiq turi. Xitoyning ramzi."),
    ("koala", "Koala — Avstraliyadagi mayin hayvon. Evkalipt barglarini yeydi."),
    ("kanguru", "Kenguru — Avstraliya ramzi, sumkali hayvon. Sakrab yuradi."),
    ("zirafa", "Jirafa — eng uzun bo'yli hayvon. Uzoq bo'yni bilan mashhur."),
    ("fil", "Fil — eng katta quruqlik hayvoni. Xotirasi juda yaxshi."),
    ("karkidon", "Karkidon — shoxli yirik hayvon. Janubiy Osiyo va Afrikada yashaydi."),
    ("begemot", "Begemot — katta og'izli yirik hayvon. Daryolarda yashaydi."),
    ("maymun", "Maymun — odamga o'xshash, epchil hayvon. O'rmonlarda yashaydi."),
    ("gavhar bobo", "Arslonlar guruhi — poda deb ataladi. Sherlar oila bo'lib yashaydi."),
    ("kurka", "Kurka — katta xonaki qush, go'shti uchun boqiladi."),
    ("g'oz", "G'oz — suvda yashashni yaxshi ko'radigan parranda."),
    ("o'rdak", "O'rdak — suzuvchi parranda. Ko'llarda yashaydi."),

    # ---------- O'SIMLIKLAR ----------
    ("daraxt", "Daraxt — ko'p yillik yirik o'simlik. Ildizi, tanasi, shoxlari bor. Havoni tozalaydi."),
    ("gul", "Gul — o'simlikning go'zal, rangli qismi. Hasharotlarni o'ziga jalb qiladi."),
    ("atirgul", "Atirgul — go'zallik va sevgi ramzi bo'lgan xushbo'y gul."),
    ("lola", "Lola — bahorda ochiladigan go'zal gul. O'zbekistonning ramzi!"),
    ("paxta", "Paxta — O'zbekistonning «oq oltini». Kiyim tayyorlash uchun ishlatiladi."),
    ("bug'doy", "Bug'doy — nondan tayyorlanadigan asosiy don. Non — hayot asosi!"),
    ("sholi", "Sholi — guruch olinadigan don. Palovning asosiy masallig'i."),
    ("makkajo'xori", "Makkajo'xori — sariq donli o'simlik. Popkorn shundan tayyorlanadi!"),
    ("olma", "Olma — eng keng tarqalgan meva. «Kuniga bitta olma — shifokor kerakmas» deyishadi."),
    ("anor", "Anor — qizil donli foydali meva. O'zbekistonning ramzlaridan biri."),
    ("uzum", "Uzum — shirin dastalarda o'sadigan meva. Mayiz va sharob undan tayyorlanadi."),
    ("qovun", "Qovun — yozda pishadigan shirin xandon meva. Xorazm qovunlari mashhur!"),
    ("tarvuz", "Tarvuz — yozning eng sevimli mevasi. Ichki qismi qizil va suvli."),
    ("o'rik", "O'rik — o'rtasi qattiq bo'lgan shirin meva. Quritilgani — qurum."),
    ("gilos", "Gilos — mayda, shirin qizil meva."),
    ("behi", "Behi — xushbo'y, qattiq meva. Murabbo tayyorlanadi."),
    ("nok", "Nok — shirin, pastga tomon kengaygan meva."),
    ("bodom", "Bodom — yong'oq turi. Mazali va foydali."),
    ("pista", "Pista — O'zbekistonda yetishtiriladigan qimmatbaho yong'oq."),
    ("yong'oq", "Yong'oq — miya faoliyati uchun foydali yong'oq turi."),
    ("chigit", "Chigit — paxta doni. Yog' olinadi."),
    ("sabzi", "Sabzi — to'q sariq ildizmeva. Palovning asosiy qismi."),
    ("piyoz", "Piyoz — har qanday taomga solinadigan sabzavot. Ko'z yosh keltiradi!"),
    ("kartoshka", "Kartoshka — dunyoda eng ko'p iste'mol qilinadigan sabzavotlardan biri."),
    ("pomidor", "Pomidor — qizil mevali sabzavot. Sos va salatlarda ishlatiladi."),
    ("bodring", "Bodring — yashil, suvli sabzavot. Salatlarda ishlatiladi."),
    ("qalampir", "Qalampir — achchiq yoki shirin bo'ladigan sabzavot."),
    ("karam", "Karam — boshoqli sabzavot. Solanka va salatda ishlatiladi."),
    ("choy o'simligi", "Choy o'simligi — barglaridan choy tayyorlanadi. O'zbekistonda choy — mehmondo'stlik ramzi!"),
    ("lavlagi", "Lavlagi — qizil ildizmeva. Shakar olinishi ham mumkin."),

    # ---------- SOG'LIQ ----------
    ("yurak", "Yurak — qonni butun tanaga haydaydigan mushak organ. Bir daqiqada ~70 marta uradi."),
    ("miya", "Miya — tanani boshqaradigan organ. O'ylash, eslash, his qilish shu yerda."),
    ("qon", "Qon — kislorod va ozuqa moddalarni tanaga tarqatadigan suyuqlik."),
    ("o'pka", "O'pka — nafas olish organi. Havodan kislorod oladi."),
    ("jigarrang", "Jigar — tanani tozalaydigan qimmatbaho organ. Kimyoviy «zavod»."),
    ("oshqozon", "Oshqozon — ovqatni hazm qilishni boshlaydigan organ."),
    ("tish", "Tish — ovqatni chaynash uchun zarur. Kuniga 2 marta yuvish kerak!"),
    ("teri", "Teri — tananing eng katta organi. Himoya qatlami."),
    ("immunitet", "Immunitet — tananing kasalliklarga qarshi himoya tizimi. Vitaminlar uni kuchaytiradi."),
    ("gripp", "Gripp — viruslar keltirib chiqaradigan kasallik. Ko'p suyuqlik ichish tavsiya etiladi."),
    ("temperatura", "Tana harorati — sog'lom odamda ~36,6°C. 37°C dan oshsa — isitma."),
    ("dori", "Dori — kasallikni davolashda ishlatiladigan modda. Faqat shifokor ko'rsatmasi bilan!"),
    ("vaksina", "Vaksina — tanani kasallikka qarshi o'rgatadigan emlash. Kasallikdan himoya qiladi."),
    ("shifokor", "Shifokor — kasallarni davolaydigan mutaxassis. Har doim yordamga tayyor!"),
    ("tibbiyot", "Tibbiyot — inson salomatligini o'rganadigan va davolaydigan fan."),
    ("sog'lom ovqatlanish", "Sog'lom ovqatlanish — meva, sabzavot va to'yimli taomlarni muntazam iste'mol qilish. Salomatlik garovi!"),

    # ---------- OVQAT ----------
    ("osh", "Palov (osh) — guruch, sabzi va go'shtdan tayyorlanadigan O'zbekistonning asosiy taomi."),
    ("manti", "Manti — bug'da pishiriladigan go'shtli xamir taom."),
    ("chuchvara", "Chuchvara — mayda qaynatilgan xamir va go'shtli taom."),
    ("somsa", "Somsa — tandirda pishiriladigan go'shtli pirog."),
    ("shashlik", "Shashlik — ko'mirda pishiriladigan go'sht kabobi. Sayr qilishda sevimli taom!"),
    ("lag'mon", "Lag'mon — uzun xamir va go'shtli uyg'ur taomi."),
    ("mastava", "Mastava — guruch va sabzavotli sho'rva."),
    ("sho'rva", "Sho'rva — go'sht va sabzavotlar qaynatilgan suyuq taom."),
    ("qaynatma", "Qaynatma — go'sht qaynatmasidan tayyorlanadigan to'yimli sho'rva."),
    ("somsa tarixi", "Somsa — Sharqda qadimdan tayyorlanadigan taom. Tandirda pishiriladi."),
    ("kabob", "Kabob — go'shtdan tayyorlanadigan taomlar oilasi. Uskara kabobi Soltan"+"larda mashhur."),
    ("non", "Non — asosiy oziq-ovqat. O'zbekistonda non — muqaddas!"),
    ("patir", "Patir — yog'da pishiriladigan yumshoq non."),
    ("lochira", "Lochira — maxsus xamirdan tayyorlanadigan yupqa non."),
    ("guruch", "Guruch — sholidan olinadigan don. Palovning asosi."),
    ("sut", "Sut — sigirdan olinadigan foydali ichimlik. Kaltsiyga boy."),
    ("qatiq", "Qatiq — sutdan tayyorlanadigan fermentlangan ichimlik. Ovqat hazmiga yordam beradi."),
    ("suzma", "Suzma — qatiqdan tayyorlanadigan quyuq sut mahsuloti."),
    ("qaymoq", "Qaymoq — sutning yog'li qatlami. Choy bilan mazali!"),
    ("sariyog'", "Sariyog' — sutdan tayyorlanadigan yog'. Non bilan yeyiladi."),
    ("pishloq", "Pishloq — sutdan tayyorlanadigan qattiq mahsulot."),
    ("asal", "Asal — asalarilar tayyorlaydigan shirin va shifobaxsh mahsulot."),
    ("murabbo", "Murabbo — mevalardan shakar bilan tayyorlanadigan qiyom."),
    ("choy ichish", "Choy — O'zbekistonda mehmondo'stlik ramzi. Choysiz suhbat bo'lmaydi!"),
    ("qahva", "Qahva — tonuvchi ichimlik. Ko'p ichish yurakka zarar bo'lishi mumkin."),
    ("limonad", "Limonad — gazlangan shirin ichimlik."),
    ("sharbat", "Sharbat — mevalardan tayyorlanadigan tabiiy ichimlik."),
    ("muzqaymoq", "Muzqaymoq — sovuq shirin desert. Yozning sevimli taomi!"),
    ("xolva", "Xolva — kunjut va shakardan tayyorlanadigan shiriniy."),
    ("sumalak", "Sumalak — Navro'zda bug'doy unib chiqarib tayyorlanadigan shirin taom."),
    ("novvoy", "Novvoy — non yopadigan usta. Non — xalqimizning oq oltini."),
]