# -*- coding: utf-8 -*-
"""
MEGA BILIM — E QISM: KINO, ANIME, MUSIQA, SAN'AT, SPORT
"""

KNOWLEDGE = [
    # ---------- KINO ----------
    ("kinematograf", "Kinematograf — harakatlanuvchi tasvirlar san'ati. «Kino» so'zi shundan kelgan."),
    ("gollivud", "Gollivud — Los-Anjelesdagi mashhur kino markazi. Dunyodagi eng mashhur kinostudiylar shu yerda."),
    ("bollywood", "Bollywood — Hindistonning kino sanoati. Har yili eng ko'p film suratga olinadi!"),
    ("nimkino", "Nimkino (short film) — qisqa metrajli film. 40 daqiqagacha davom etadi."),
    ("dokumental", "Dokumental film — real voqealarga asoslangan film."),
    ("multfilm nima", "Multfilm — bolalar va kattalar uchun jonlantirilgan film."),
    ("treyler", "Treyler — filmning oldindan ko'rsatiladigan qisqa namoyishi."),
    ("poster", "Poster — filmning reklama plakati."),
    ("kasting", "Kasting — filmlarga aktyor saralash jarayoni."),
    ("sahna", "Sahna — film suratga olinadigan joy yoki pyesa ko'rsatiladigan maydon."),
    ("kadr", "Kadr — kino yoki videoning bitta surati."),
    ("montaj", "Montaj — film kadrlarini ketma-ketlikda yopishtirish jarayoni."),
    ("ovoz effekti", "Ovoz effekti — filmga qo'shiladigan sun'iy tovushlar."),
    ("grif", "Special effects (SFX) — alohida kino effektlari. Portlashlar, sehrlar shu orqali yaratiladi."),
    ("goboy qahramon", "Bosh qahramon — hikoya asosiy uning atrofida quriladigan obraz."),
    ("antagonist", "Antagonist — hikoyadagi asosiy raqib yoki yovuz obraz."),
    ("dublaj qilish", "Dublyaj — filmini boshqa tilga ovozlashtirish."),
    ("sinkron", "Sinkron tarjima — ko'p tilli filmlarda ovozni birga uzatish."),
    ("kino nagradi", "Oskar — AQSH kino akademiyasining eng nufuzli film mukofoti."),
    ("kan gulm", "Kan festivali — Fransiyadagi nufuzli kino festivali. «Oltin palma» shu yerda beriladi."),
    ("berlinale", "Berlinale — Berlindagi mashhur kino festivali."),
    ("venetsiya festivali", "Venetsiya kino festivali — dunyodagi eng qadimiy kino festivali."),
    ("serial", "Serial — ko'p qismdan iborat kino asar. Har qism alohida davom etadi."),
    ("efir", "Efir — telekanal orqali jonli yoki yozib ko'rsatish."),
    ("qisqa video", "Qisqa video — bir necha daqiqalik video kontent. TikTok va Reels olami."),
    ("anime janrlari", "Anime janrlari — shonen (bolalar uchun), seinen (kattalar uchun), shojo (qizlar uchun) kabilar."),
    ("shonen", "Shonen — yoshlar uchun mo'ljallangan anime turi. Naruto, Dragon Ball — mashhur misollar."),
    ("seinen", "Seinen — kattalar uchun jiddiy anime turi."),
    ("manga", "Manga — yapon qora-oq komiksi. Ko'p anime mangadan olingan."),
    ("muxlis", "Muxlis — filmlar, sport yoki san'atni yaxshi ko'radigan ishqiboz."),
    ("repo", "Remeyk — eski filmining yangi versiyasi."),
    ("prequel", "Prikvel — asl filmdan oldingi voqealarni ko'rsatadigan film."),
    ("sikvel", "Sikvel — davomiy film (2-qism)."),
    ("franchayz", "Franchayz — bir olamga tegishli filmlar seriyasi. Marvel — misol."),
    ("kino matn", "Film ssenariysi — film suratga olinadigan matn."),

    # ---------- SAN'AT ----------
    ("san'at", "San'at — go'zallik yaratish faoliyati. Rasm, musiqa, kino, teatr — san'at turlari."),
    ("rasm", "Rasm — bo'yoq yoki qalam bilan chizilgan surat."),
    ("rang", "Rang — yorug'likning ko'zga ko'rinadigan xususiyati. Qizil, ko'k, sariq — asosiy ranglar."),
    ("muzey", "Muzey — tarixiy va san'at asarlari saqlanadigan joy."),
    ("teatr", "Teatr — sahnada jonli o'ynaladigan san'at turi."),
    ("sirk", "Sirk — ajoyib chiqishlar ko'rsatiladigan o'yin-kulgi joyi."),
    ("haykaltaroshlik", "Haykaltaroshlik — tosh, loy va boshqa materiallardan shakl yasash san'ati."),
    ("arxiv", "Arxitektura — bino va inshootlarni loyihalash san'ati."),
    ("fotografiya", "Fotografiya — suratga olish san'ati. «Yorug'lik bilan chizish»."),
    ("qo'shiq", "Qo'shiq — kuylash uchun mo'ljallangan musiqa asari."),
    ("asta", "Kamalak ranglari — qizil, to'q sariq, sariq, yashil, ko'k, havorang. Yomg'irdan keyin ko'rinadi."),

    # ---------- MUSIQA ----------
    ("musiqa", "Musiqa — ohang va ritm bilan ifodalanadigan san'at. Insonga ta'sir qilish kuchi bor!"),
    ("ritm", "Ritm — musiqadagi teng vaqt oralig'idagi urishlar."),
    ("ohang", "Ohang (melo diya) — musiqaning asosiy kuylash qismi."),
    ("guitar", "Gitara — 6 torli cholg'u asbobi. Rok musiqa ramzi."),
    ("pianino", "Pianino — klavishli cholg'u. Ko'p ming yillik musiqalar shu asbobda yozilgan."),
    ("doira", "Doira — o'zbek va sharq musiqasida ishlatiladigan urma cholg'u."),
    ("rubob", "Rubob — o'zbek xalq cholg'usi. «Cholg'ular shohi» deb ataladi."),
    ("dutor", "Dutor — o'zbekning ikki torli xalq cholg'usi."),
    ("nay", "Nay — yog'och yoki qamishdan yasalgan puflab chalinadigan cholg'u."),
    ("skripka", "Skripka — torli-kamonli cholg'u. Orkestrning asosi."),
    ("baraban", "Baraban — urib chalinadigan cholg'u. Ritm beradi."),
    ("saksafon", "Saksafon — puflab chalinadigan yog'och cholg'u. Jazz musiqasi ramzi."),
    ("opera", "Opera — qo'shiq va drama uyg'unlashgan sahna san'ati."),
    ("balet", "Balet — raqs orqali hikoya qiladigan sahna san'ati."),
    ("jazz", "Jazz — AQSHda tug'ilgan musiqiy uslub. Bepul improvizatsiya bilan mashhur."),
    ("rok", "Rok — kuchli gitara va barabanli musiqa uslubi."),
    ("pop musiqasi", "Pop musiqa — xit va oson quloqqa yaqin ommaviy musiqa."),
    ("rep", "Rep — qofiyalangan tez matn aytish uslubi."),

    # ---------- SPORT ----------
    ("sport", "Sport — jismoniy mashqlar va musobaqalar. Salomatlik garovi!"),
    ("olimpiada", "Olimpiada o'yinlari — dunyodagi eng katta sport musobaqasi. Har 4 yilda o'tkaziladi."),
    ("futbol jamoasi", "Futbol — 11 tadan iborat ikki jamoa o'ynaydigan eng mashhur sport turi."),
    ("basketbol", "Basketbol — savatga to'p tashlash o'yini. Har jamoada 5 o'yinchi."),
    ("voleybol", "Voleybol — to'r orqali to'p uzatish o'yini. Har jamoada 6 o'yinchi."),
    ("tennis", "Tennis — raketa bilan to'p urish o'yini."),
    ("bokschilik", "Boks — qo'l bilan urish sporti. Jismoniy tayyorgarlik talab qiladi."),
    ("dzyudo", "Dzyudo — Yaponiyadan kelgan kurash san'ati."),
    ("karate", "Karate — Yaponiyadan kelgan himoya sporti."),
    ("suzish", "Suzish — suvda harakatlanish sporti. Butun tana mushaklarini mustahkamlaydi."),
    ("yugurish", "Yugurish — eng oddiy va foydali sport turi. Ertalabki yugurish — tetiklik manbai!"),
    ("velosport", "Velosport — velosipedda musobaqa qilish."),
    ("shaxmat o'yini", "Shaxmat — 64 katakli doskada o'ynaladigan fikr sporti. «Aql o'yini»."),
    ("shashka", "Shashka — oddiy qoidalarli doska o'yini. Fikrlashni rivojlantiradi."),
    ("ko'tara", "Og'ir atletika — og'irliklarni ko'tarish sporti."),
    ("uchkur", "Uchqur — shamol ta'sirida harakatlanadigan suv sporti. Jismoniy tayyorgarlikni oshiradi."),
    ("stol tennisi", "Stol tennisi — stol ustida raketa bilan o'ynaladigan tezkor o'yin."),
    ("badminton", "Badminton — qushcha (volan) bilan o'ynaladigan o'yin."),
    ("kurash musobaqasi", "Kurash — o'zbek xalqining qadimiy sporti. Dunyoda tan olingan!"),
    ("chim", "Chim ustidagi futbol — «sport qiroli» deb ataladi."),
    ("marafon", "Marafon — 42 km 195 m masofaga yugurish musobaqasi."),
]