# -*- coding: utf-8 -*-
"""
MEGA BILIM — F QISM: TARIX, IQTISOD, MADANIYAT, URF-ODATLAR
"""

KNOWLEDGE = [
    # ---------- UMUMIY TARIX ----------
    ("tarix", "Tarix — o'tmish voqealarini o'rganadigan fan. U o'tmishdan saboq beradi."),
    ("davr", "Davr — tarixning bir qismi. Qadimgi, o'rta va yangi davrlar bor."),
    ("sivilizatsiya", "Sivilizatsiya — rivojlangan jamiyat. Misr, Rim, Xitoy — qadimiy sivilizatsiyalar."),
    ("imperiya", "Imperiya — ko'p xalqlarni birlashtirgan qudratli davlat."),
    ("pyraimda", "Piramidalar — Misrda qurilgan ulkan qabriston inshootlari. Dunyoning yetti mo'jizasidan biri."),
    ("rim imperiyasi", "Rim imperiyasi — qadimiy dunyoning qudratli davlati. Yevropa madaniyatiga katta ta'sir ko'rsatgan."),
    ("turon", "Buyuk ipak yo'li bo'ylab qadimda Turon — Markaziy Osiyoda yashagan xalqlarning umumiy nomi."),
    ("kushon", "Kushonlar — qadimda Markaziy Osiyoda yashagan buyuk davlat."),
    ("xuroson", "Xuroson — qadimda Buyuk ipak yo'lidagi tarixiy viloyat."),
    ("sog'd", "So'g'd — qadimda O'zbekiston hududidagi boy savdo mamlakati. Samarqand uning markazi edi."),
    ("amir temur", "Amir Temur — buyuk sarkarda va davlat arbobi (1336—1405). Samarqandni dunyo markaziga aylantirgan."),
    ("temuriylar", "Temuriylar — Amir Temur avlodlari. Ularning davrida ilm-fan va san'at gullab-yashnagan."),
    ("ulug'bek", "Mirzo Ulug'bek — buyuk astronom va hukmdor (1394—1449). Rasadxonasi bilan mashhur."),
    ("alisher navoiy", "Alisher Navoiy — buyuk shoir va mutafakkir (1441—1501). O'zbek adabiyotining asoschisi."),
    ("bobur", "Zahiriddin Muhammad Bobur — buyuk shoir, sarkarda va Boburiy saltanatining asoschisi (1483—1530)."),
    ("avitsenna", "Ibn Sino (Avitsenna) — buyuk tabib va faylasuf (980—1037). «Tib qonunlari» kitobi bilan mashhur."),
    ("al xorazmiy", "Al-Xorazmiy — algebra asoschisi (780—850). «Algoritm» so'zi uning nomidan kelgan!"),
    ("beruniy", "Abu Rayhon Beruniy — buyuk olim va qomusiy bilimdon (973—1048)."),
    ("farg'oniylar", "Al-Farg'oniy — buyuk astronom (798—865). Yerning diametrini aniq hisoblagan."),
    ("imom buxoriy", "Imom Buxoriy — hadis ilmi sultoni (810—870). «Al-Jome' as-Sahih» asari bilan mashhur."),
    ("at termiziy", "Imom Termiziy — buyuk muhaddis olim."),
    ("buxoro ilm", "Buxoro — qadimda «ilmlar shahri» deb atalgan. Ko'plab olimlarning vatani."),
    ("madrasa", "Madrasa — qadimiy musulmon o'quv dargohi. Registon madrasalari mashhur."),
    ("xonlardavri", "Xonliklar — 16—19-asrlarda O'zbekistonda bo'lgan Buxoro, Xiva va Qo'qon xonliklari."),
    ("jadidlar", "Jadidlar — 20-asr boshlarida ma'rifat uchun kurashgan o'zbek ziyolilari."),
    ("mustaqillik", "O'zbekiston mustaqilligi — 1991-yil 1-sentabrda e'lon qilingan. O'shandan beri 1-sentabr — Mustaqillik kuni!"),
    ("konstitutsiya", "Konstitutsiya — davlatning asosiy qonuni. O'zbekiston Konstitutsiyasi 1992-yilda qabul qilingan."),
    ("bayroq", "O'zbekiston bayrog'i — ko'k, oq va yashil ranglardan. 12 yulduz va yarim oy tasvirlangan."),
    ("gerb", "Gerb — davlatning belgisi. O'zbekiston gerbida Xumo qushi va quyosh tasvirlangan."),
    ("madhiya", "Madhiya — davlatning tantanali qo'shig'i. Har mamlakatda alohida bo'ladi."),

    # ---------- IQTISODIYOT / BIZNES ----------
    ("iqtisodiyot", "Iqtisodiyot — boylik ishlab chiqarish, taqsimlash va iste'mol qilish tizimi."),
    ("pul", "Pul — tovarlar o'lchovi bo'lgan vosita. O'zbekistonda so'm ishlatiladi."),
    ("so'm", "So'm — O'zbekiston milliy valyutasi."),
    ("bank", "Bank — pul saqlash, kredit berish va to'lov qilish muassasasi."),
    ("kredit", "Kredit — bankdan qarzga pul olish va foiz bilan qaytarish."),
    ("depozit", "Depozit — bankda saqlash uchun qo'yilgan pul, foiz oladi."),
    ("soliq", "Soliq — davlatga to'lanadigan majburiy to'lov."),
    ("bozor iqtisodiyoti", "Bozor — tovarlar sotiladigan joy. Bozor iqtisodiyoti — talab va taklif asosidagi tizim."),
    ("narx", "Narx — tovarning qancha turishini ko'rsatadigan miqdor."),
    ("chegirma", "Chegirma (skidka) — narxning pasaytirilgan holati. Xarid qilish uchun yaxshi fursat!"),
    ("biznes", "Biznes — foyda olish uchun faoliyat yuritish. Tadbirkorlik ham deyiladi."),
    ("tadbirkor", "Tadbirkor — biznes yurituvchi, tavakkal qiladigan odam. Iqtisodiyot dvigateli."),
    ("startap", "Startap — yangi g'oya asosida boshlangan biznes loyihasi."),
    ("investitsiya", "Investitsiya — kelajakda foyda olish uchun qo'yilgan mablag'."),
    ("foyda", "Foyda — daromaddan xarajatlar chiqarilganda qolgan qism."),
    ("zarar", "Zarar — xarajatlar daromaddan oshib ketgandagi holat."),
    ("daromad", "Daromad — sotishdan tushgan pul miqdori."),
    ("import", "Import — chetdan tovar olib kelish."),
    ("eksport", "Eksport — mahalliy tovarni chetga sotish."),
    ("valyuta", "Valyuta — xorijiy pul birligi. Dollar, evro — valyutalar."),
    ("dollar", "Dollar — AQSH valyutasi. Dunyo bozorida asosiy valyuta."),
    ("evro", "Evro — Yevropa Ittifoqining yagona valyutasi."),
    ("inflation", "Inflyatsiya — narxlarning oshib borishi. Pulning qadrsizlanishi."),
    ("byudjet", "Byudjet — daromad va xarajatlarning rejasi. Davlat va oila byudjeti bor."),
    ("maosh", "Maosh — ish uchun to'lanadigan haq."),
    ("ishsizlik", "Ishsizlik — ishi yo'q odamlar holati. Davlat unga qarshi kurashadi."),
    ("kashf", "Mahsulot — sotiladigan tovar yoki xizmat."),
    ("reklama", "Reklama — mahsulotni tanitish usuli. «Reklama — savdo dvigateli»."),
    ("savdo", "Savdo — tovar va xizmatlarni almashtirish jarayoni."),
    ("tender", "Tender — davlat xaridlari bo'yicha tanlov."),

    # ---------- MADANIYAT / URF-ODAT ----------
    ("urf-odat", "Urf-odat — xalqning an'anaviy qadriyatlari. Har xalqning o'ziga xos urf-odatlari bor."),
    ("navro'z", "Navro'z — bahor kirib kelishi bayrami (21-mart). Yangi yil boshlanishi deb hisoblanadi."),
    ("hayit", "Hayit — musulmonlarning bayramlari: Ramazon hayiti va Qurbon hayiti."),
    ("mehmondo'stlik", "Mehmondo'stlik — o'zbek xalqining eng go'zal fazilatlari. Mehmon — aziz!"),
    ("choyxona", "Choyxona — odamlar choy ichib, suhbatlashadigan joy. O'zbek madaniyatining bir qismi."),
    ("dasturxon", "Dasturxon — yozilgan mato ustidagi taom maydoni. O'zbekistonda to'kin dasturxon — orzu!"),
    ("to'y", "To'y — nikoh va boshqa tantanalar. O'zbek to'ylari katta va quvnoq o'tadi."),
    ("beshik to'yi", "Beshik to'yi — yangi tug'ilgan chaqaloq sharafiga o'tkaziladigan marosim."),
    ("sumalak tayyorlash", "Sumalak — Navro'zda qishloqlarda tonggacha tayyorlanadigan shirin taom."),
    ("halq o'yinlari", "Milliy o'yinlar — kurash, uloq, qiz quvish kabi o'zbek xalq o'yinlari."),
    ("asrlar merosi", "Merоs — ajdodlardan qolgan qadriyatlar va boyliklar."),
    ("mahalla", "Mahalla — o'zbek jamiyatining asosiy bo'g'ini. Hamjihatlik ramzi."),
    ("ota-ona", "Ota-ona — farzand tarbiyasi uchun eng mas'ul insonlar. Ularga hurmat — farzlik burchi."),
    ("ustoz", "Ustoz — bilim va hunar o'rgatuvchi shaxs. «Ustoz — otadan ulug'» deganlar."),
    ("do'stlik", "Do'stlik — inson hayotidagi eng qimmatli fazilat. Do'st qiyinchilikda sinovdan o'tadi."),
    ("halollik", "Halollik — rostgo'ylik va to'g'rilik. Xalqimizning eng yuksak fazilati."),
    ("sabr", "Sabr — og'ir vaziyatlarda chidamlilik. «Sabr — zafar» deganlar."),
    ("olijanoblik", "Saxiy — beruvchan, qo'li ochiq inson. Saxovat — yaxshilik belgisi."),

    # ---------- BOSHQALAR ----------
    ("baxsh", "Baxshi — xalq qo'shiqlarini ijro etuvchi sozanda. Dostonlarni aytadi."),
    ("lapar", "Lapar — ikki kishi o'rtasidagi qiziqarli qo'shiq bahsi."),
    ("yalla", "Yalla — o'zbek xalq musiqasi janri. Raqs bilan ijro etiladi."),
    ("skazka", "Ertak — bolalar uchun mo'ljallangan sehrli hikoya. Qahramonlar va sehrli narsalar ishtirok etadi."),
    ("masal", "Masal — saboq beruvchi qisqa hikoya. Qahramonlari ko'pincha hayvonlar."),
    ("maqol", "Maqol — xalq donoligini ifodalovchi qisqa ibora."),
    ("doston", "Doston — xalq og'zaki ijodining katta asari. «Alpomish» — o'zbek xalq dostoni."),
    ("rivoyat", "Rivoyat — ming yillar davomida og'izdan og'izga o'tgan hikoya."),
    ("aqlli taxta", "Loyiha — reja asosida amalga oshiriladigan ish. Yaxshi loyiha — muvaffaqiyat kaliti."),
]