# -*- coding: utf-8 -*-
"""
MEGA BILIM — B QISM: FAN (FIZIKA, KIMYO, MATEMATIKA, KOSMOS, TABIAT)
"""

KNOWLEDGE = [
    # ---------- FIZIKA ----------
    ("kuch", "Kuch — jismga ta'sir etib, uning tezligini o'zgartira oladigan fizik kattalik. Nyutonlarda o'lchanadi."),
    ("tezlik", "Tezlik — jismning vaqt birligida bosib o'tgan masofasi. km/soat yoki m/s da o'lchanadi."),
    ("masofa", "Masofa — ikki nuqta orasidagi uzunlik. Kilometr, metr kabi birliklarda o'lchanadi."),
    ("vaqt", "Vaqt — voqealarning ketma-ketligini o'lchaydigan fizik kattalik. Oddiy hayotda sekund, minut, soat ishlatamiz."),
    ("energiya", "Energiya — ish bajarish qobiliyati. Kinetik, potensial, issiqlik, elektr energiyasi bor."),
    ("massa", "Massa — jismdagi modda miqdori. Kilogrammlarda o'lchanadi."),
    ("og'irlik", "Og'irlik — Yerning jismga tortish kuchi. Nyutonda o'lchanadi, massadan farq qiladi."),
    ("zichlik", "Zichlik — moddaning hajm birligidagi massasi. Suv zichligi 1 g/sm³."),
    ("bosim", "Bosim — yuzaga ta'sir qiladigan kuch. Paskallarda o'lchanadi. Pastki qatlamlarda bosim katta."),
    ("harorat", "Harorat — jismning issiq-sovuqligini ko'rsatadigan kattalik. Daraajalarda o'lchanadi."),
    ("issiqlik", "Issiqlik — energiyaning bir jismdan ikkinchisiga o'tish shakli. Quyoshdan Yerga keladi."),
    ("tovush", "Tovush — havo yoki boshqa muhitda tarqaladigan tebranish. Tezligi havoda ~340 m/s."),
    ("yorug'lik tezligi", "Yorug'lik tezligi — sekundiga ~300 000 km. Koinotdagi eng katta tezlik."),
    ("magnit", "Magnit — temir kabi metallarni o'ziga tortadigan jism. Kompaslar magnit asosida ishlaydi."),
    ("magnit maydoni", "Magnit maydoni — magnit atrofidagi ta'sir zonasi. Yerning ham o'z magnit maydoni bor."),
    ("elektr toki", "Elektr toki — zaryadlangan zarrachalarning tartibli harakati. Amperda o'lchanadi."),
    ("kuchlanish", "Kuchlanish — elektr zanjirda zaryadlarni harakatlantiradigan bosim. Voltlarda o'lchanadi."),
    ("qarshilik", "Qarshilik — elektr tokiga ko'rsatiladigan to'siq. Omda o'lchanadi."),
    ("quvvat", "Quvvat — vaqt birligida bajarilgan ish. Vattlarda o'lchanadi."),
    ("suyuqlik", "Suyuqlik — oquvchan holatidagi modda. Suv, sut, yog' — suyuqliklar."),
    ("muz", "Muz — suvning muzlagan qattiq holati. 0°C da muzlaydi."),
    ("bug'", "Bug' — suvning gaz holati. Qaynaganda suv bug'ga aylanadi."),
    ("qaynash", "Qaynash — suyuqlikning butun hajmida bug'lanishi. Suv 100°C da qaynaydi."),
    ("erish", "Erish — qattiq moddaning suyuqlikka aylanishi. Muz 0°C da eriydi."),
    ("difuziya", "Difuziya — moddalarning o'z-o'zidan aralashishi. Choy damlaganda shakar shunday tarqaladi."),
    ("inertsiya", "Inersiya — jismning o'z harakat holatini saqlash xususiyati. Avtobus tormozlaganda oldinga siljishimiz shu tufayli."),
    ("friksiya", "Ishqalanish kuchi — jismlar sirpanishiga qarshilik qiladigan kuch."),
    ("tortishish", "Tortishish kuchi — jismlarning bir-birini o'ziga tortishi. Yer bizni shu kuch bilan ushlab turadi."),
    ("kosmik tezlik", "Kosmik tezlik — jismning Yer orbitasiga chiqishi uchun kerakli tezlik (~7,9 km/s)."),
    ("atom", "Atom — materiyaning eng kichik zarrasi. Yadro va elektronlardan iborat."),

    # ---------- KIMYO ----------
    ("kimyo nima", "Kimyo — moddalar tarkibi, xossalari va o'zgarishlarini o'rganadigan fan."),
    ("molekula", "Molekula — moddaning kimyoviy xossalarini saqlovchi eng kichik zarrasi."),
    ("element", "Kimyoviy element — bir xil atomlardan tashkil topgan modda. Vodorod, kislorod, temir — elementlar."),
    ("vodorod", "Vodorod — eng yengil kimyoviy element. Belgisi H. Quyosh asosan vodoroddan iborat."),
    ("kislorod", "Kislorod — nafas olish uchun zarur gaz. Belgisi O. Havoning ~21 foizi kislorod."),
    ("azot", "Azot — havoning ~78 foizini tashkil etadigan gaz. Belgisi N."),
    ("uglerod", "Uglerod — hayotning asosi. Olmos va grafit uning shakllari. Belgisi C."),
    ("temir", "Temir — metall, belgisi Fe. Qurilish va texnikada juda ko'p ishlatiladi."),
    ("oltin", "Oltin — qimmatbaho metall, belgisi Au. Zargarlik va elektronikada ishlatiladi."),
    ("kumush", "Kumush — yaltiroq qimmatbaho metall, belgisi Ag. Zargarlikda ishlatiladi."),
    ("mis", "Mis — qizg'ish metall, belgisi Cu. Elektr simlari uchun juda yaxshi."),
    ("alyuminiy", "Alyuminiy — yengil kumushrang metall, belgisi Al. Samolyot va idishlarda ishlatiladi."),
    ("suv formulasi", "Suvning kimyoviy formulasi — H2O: ikkita vodorod va bitta kislorod atomi."),
    ("tuz", "Tuz — natriy xlorid (NaCl). Oshxona tuzi oziq-ovqatda ishlatiladi."),
    ("shakar", "Shakar — kimyoviy nomi saxaroza. Shirin ta'm beradigan modda."),
    ("o'g'it", "O'g'it — o'simliklarni oziqlantirish uchun tuproqqa qo'shiladigan modda. Azotli, fosforli turlari bor."),
    ("kislota", "Kislota — vodorod tutgan kimyoviy modda. Limon sharbati tarkibida limon kislotasi bor."),
    ("asos", "Asos (ishqor) — kislota bilan reaksiyaga kirishadigan modda. Sovun tarkibida asos bor."),
    ("neytrallash", "Neytrallash — kislota va asosning bir-birini betaraf qilishi natijasida tuz va suv hosil bo'lishi."),
    ("reaksiya", "Kimyoviy reaksiya — moddalarning o'zaro ta'siri natijasida yangi moddalar hosil bo'lishi."),
    ("zang", "Zang — temirning kislorod va suv ta'sirida qizarishi. Aslida sekin kimyoviy reaksiya."),
    ("olov", "Olov — yonish jarayonida issiqlik va yorug'lik chiqaradigan jarayon. Yonish uchun kislorod kerak."),
    ("gaz", "Gaz — erkin harakatlanadigan zarrachalardan iborat modda holati. Havo — gazlar aralashmasi."),
    ("plastmassa", "Plastmassa — sun'iy yaratilgan polimer material. Yengil va mustahkam."),
    ("shisha", "Shisha — qumdan qizdirib eritib tayyorlanadigan shaffof material."),
    ("beton", "Beton — sement, qum va suv aralashmasidan tayyorlanadigan qurilish materiali."),
    ("neft", "Neft — yer ostidan olinadigan yonilg'i. Benzinning asosi."),
    ("gaz tabiiy", "Tabiiy gaz — yer ostidan olinadigan yonuvchi gaz. Uyda pishirishda ishlatiladi."),
    ("ko'mir", "Ko'mir — yer ostidan olinadigan qattiq yonilg'i. O'tmishda poyezdlar ko'mirda yurgan."),
    ("olmos", "Olmos — eng qattiq tabiiy mineral. Ugleroddan tashkil topgan."),

    # ---------- MATEMATIKA ----------
    ("algebra", "Algebra — matematikaning sonlar va belgilar bilan ishlaydigan bo'limi. Tenglamalar shu yerda o'rganiladi."),
    ("geometriya", "Geometriya — shakllar, nuqta, chiziq va ularning xossalarini o'rganadigan fan."),
    ("tenglama", "Tenglama — noma'lum sonni topish masalasi. Masalan: x + 5 = 10, x = 5."),
    ("kasr", "Kasr — sonning bir qismini ifodalaydi. Masalan, 1/2 — yarim."),
    ("foiz", "Foiz — yuzdan bir ulush, % belgisi bilan yoziladi. 50% = yarmi."),
    ("kvadrat", "Kvadrat — to'rt tomoni teng bo'lgan to'rtburchak."),
    ("uchburchak", "Uchburchak — uch tomoni va uchta burchagi bo'lgan shakl."),
    ("aylana", "Aylana — markazdan teng uzoqlikdagi nuqtalar to'plami. Radius — markazdan aylanagacha masofa."),
    ("diametr", "Diametr — aylananing markazidan o'tuvchi eng uzun to'g'ri chiziq. Radiusning 2 barobari."),
    ("pi soni", "Pi (π) — aylana uzunligining diametriga nisbati. Taxminan 3,14159..."),
    ("burchak", "Burchak — ikki to'g'ri chiziq orasidagi ochilish. Daraaja (°) bilan o'lchanadi."),
    ("to'g'ri burchak", "To'g'ri burchak — 90° ga teng burchak. Kvadrat burchaklari shunday."),
    ("sonlar", "Sonlar — hisoblash uchun ishlatiladigan belgilar. Natural, butun, kasr sonlar bor."),
    ("ko'paytma", "Ko'paytma — ikki sonning ko'paytirish natijasi. Masalan: 3×4 = 12."),
    ("bo'linma", "Bo'linma — bo'lish amalining natijasi. Masalan: 12:4 = 3."),
    ("musbat son", "Musbat son — noldan katta son. Masalan, 1, 2, 3..."),
    ("manfiy son", "Manfiy son — noldan kichik son, minus belgisi bilan. Masalan, -5."),
    ("daraja", "Daraja — sonning o'z-o'ziga ko'paytirilishi. Masalan, 2³ = 8."),
    ("kvadrat ildiz", "Kvadrat ildiz — qaysi sonning kvadrati berilgan songa tengligini topadi. √9 = 3."),
    ("taqqoslash", "Taqqoslash — sonlarni katta-kichikligini aniqlash. > va < belgilari ishlatiladi."),

    # ---------- KOSMOS ----------
    ("koinot", "Koinot — hamma narsa: yulduzlar, sayyoralar, galaktikalar va bo'shliq. Cheksiz keng!"),
    ("galaktika", "Galaktika — milliardlab yulduzlardan iborat ulkan tizim. Bizning galaktika — Somon yo'li."),
    ("somon yo'li", "Somon yo'li — Quyosh joylashgan galaktika. Kechasi osmonda oq yo'l bo'lib ko'rinadi."),
    ("quyosh tizimi", "Quyosh tizimi — Quyosh va uning atrofida aylanadigan 8 sayyora va boshqa jismlar."),
    ("merkuriy", "Merkuriy — Quyoshga eng yaqin sayyora, eng kichik sayyora."),
    ("venera", "Venera — Quyoshdan ikkinchi sayyora. Eng issiq sayyora, bulutlar bilan qoplangan."),
    ("yer", "Yer — biz yashaydigan sayyora. Quyoshdan uchinchi sayyora, hayot bor yagona ma'lum joy."),
    ("mars", "Mars — «qizil sayyora». Ilmiy-fantastik filmlarning sevimli mavzusi!"),
    ("yupiter", "Yupiter — Quyosh tizimidagi eng katta sayyora. Katta qizil dog'i bilan mashhur."),
    ("satum", "Saturn — halqalari bilan mashhur sayyora. Uning halqalari muz va toshlardan iborat."),
    ("uran", "Uran — Quyoshdan yettinchi sayyora. «Muzli gigant» deb ataladi."),
    ("neptun", "Neptun — Quyoshdan eng uzoq sayyora. Kuchli shamollari bilan mashhur."),
    ("oy nima", "Oy — Yerning tabiiy yo'ldoshi. Tun osmonida ko'rinadi, Yer atrofida aylanadi."),
    ("yulduz nima", "Yulduz — o'z-o'zidan yorug'lik chiqaradigan ulkan gaz shari. Quyosh — yulduz."),
    ("qora tuynuk", "Qora tuynuk — tortishish kuchi shu qadar kuchliki, hatto yorug'lik ham qochib chiqa olmaydigan kosmik jism."),
    ("kometa", "Kometa — muz va changdan iborat kosmik jism, Quyoshga yaqinlashganda dum hosil qiladi."),
    ("meteor", "Meteor — atmosferaga kirganda yonadigan kosmik jism. «Uchar yulduz» deb ham ataladi."),
    ("raketa", "Raketa — kosmosga uchish uchun mo'ljallangan transport vositasi."),
    ("sputnik", "Sputnik (sun'iy yo'ldosh) — Yer orbitasida aylanadigan inson yaratgan apparat. Aloqa, GPS ishlatadi."),
    ("kosmonavt", "Kosmonavt (astronavt) — kosmosga uchgan inson. Birinchi kosmonavt — Yuriy Gagarin."),
    ("apollo", "Apollon dasturi — AQSHning Oyga odam qo'ndirish dasturi. 1969-yilda ilk marta muvaffaq bo'lgan."),
    ("neytronga", "Neytron yulduz — juda zich yulduz. Qoshiq hajmidagi moddasi tonnalab og'irlik qiladi."),

    # ---------- TABIAT ----------
    ("iqlim", "Iqlim — bir hududda uzoq yillar davomidagi ob-havo holati. Issiq, sovuq, quruq, nam turlari bor."),
    ("yomg'ir", "Yomg'ir — bulutlardan tomchilar bo'lib yog'adigan suv. O'simliklar uchun zarur."),
    ("qor", "Qor — muzlagan suv kristallaridan yog'adigan yog'in. Har bir qor gulining shakli noyob."),
    ("shamol", "Shamol — havoning harakatlanishi. Kuchli shamol tornadoga aylanishi mumkin."),
    ("elektr chaqmoq", "Chaqmoq — momaqaldiroq paytida osmonda hosil bo'ladigan elektr uchquni. Juda kuchli."),
    ("kamalak", "Kamalak — yomg'irdan keyin quyosh nuri suv tomchilarida sinishi natijasida paydo bo'ladigan rang-barang yoy."),
    ("tuproq", "Tuproq — o'simliklar o'sadigan yer qatlami. O'g'it bilan boyitiladi."),
    ("cho'l", "Cho'l — yomg'ir juda kam yog'adigan quruq hudud. Qizilqum — O'zbekistondagi cho'l."),
    ("o'rmon", "O'rmon — ko'p daraxtlar o'sadigan maydon. Yer o'pkasi deb ataladi."),
    ("sahro", "Sahro — juda katta qumli cho'l. Sahroi Kabir — Afrikadagi eng katta sahro."),
    ("vodiy", "Vodiy — tog'lar orasidagi pastlik. Farg'ona vodiysi — eng go'zal vodiy."),
    ("tog' tizmasi", "Tog' tizmasi — ketma-ket joylashgan tog'lar zanjiri."),
    ("qor cho'qqisi", "Cho'qqi — tog'ning eng baland nuqtasi."),
    ("sharshara", "Sharshara — balandlikdan tik tushadigan suv. Go'zal manzara!"),
    ("buloq", "Buloq — yer ostidan er yuzasiga chiqadigan suv manbai."),
    ("suv ombori", "Suv ombori — suv yig'ish uchun qurilgan sun'iy katta hovuz. Chorvoq — bunday ombor."),
    ("ekvator", "Ekvator — Yerning o'rtasidan o'tuvchi xayoliy chiziq. Eng issiq hududlar uning atrofida."),
    ("qutb", "Qutb — Yerning eng shimoliy (shimoliy qutb) va eng janubiy (janubiy qutb) nuqtalari. U yerda hamisha sovuq."),
    ("materik", "Materik — katta quruqlik massivi. Osiyo eng katta materik."),
    ("orol", "Orol — hamma tomondan suv bilan o'ralgan quruqlik. Maldiv orollari mashhur."),
]