# -*- coding: utf-8 -*-
"""
MEGA BILIM — D QISM: TEXNIKA, IT, DASTURLASH, INTERNET
"""

KNOWLEDGE = [
    # ---------- KOMPYUTER / TEXNIKA ----------
    ("protsessor", "Protsessor — kompyuterning «miyasi». Barcha hisob-kitoblarni bajaradi."),
    ("xotira", "Operativ xotira (RAM) — kompyuter ishlayotganda ma'lumotni vaqtincha saqlaydi."),
    ("qattiq disk", "Qattiq disk (HDD/SSD) — fayllar doimiy saqlanadigan xotira."),
    ("videokarta", "Videokarta — ekranda tasvirni chizadigan qurilma. O'yinlar uchun juda muhim."),
    ("monitor", "Monitor — kompyuter natijalarini ko'rsatadigan ekran."),
    ("klaviatura", "Klaviatura — matn kiritish qurilmasi."),
    ("sichqoncha", "Sichqoncha (maus) — kursorni boshqaradigan qurilma."),
    ("printer", "Printer — hujjatlarni qog'ozga bosib chiqaradigan qurilma."),
    ("skaner", "Skaner — qog'ozdagi rasm/matnni kompyuterga o'tkazadi."),
    ("noutbuk", "Noutbuk — ko'chma kompyuter. Har qayerda ishlash mumkin."),
    ("planshet", "Planshet — sensorli ekranli ko'chma qurilma."),
    ("smartfon", "Smartfon — zamonaviy telefon. Internet, kamera, ilovalar — hammasi ichida."),
    ("mikrofon", "Mikrofon — ovozni qabul qilib, elektr signaliga aylantiradi."),
    ("kolonka", "Kolonka (sabvufer) — ovozni kuchaytirib chiqaradigan qurilma."),
    ("naushnik", "Naushnik — quloqqa taqiladigan karnay. Ovozni faqat siz eshitasiz."),
    ("kamera", "Kamera — surat va video olish qurilmasi. Telefondagi kameralar juda rivojlangan."),
    ("batareya", "Batareya — qurilmani elektr bilan ta'minlaydigan energiya manbai."),
    ("zaryadka", "Zaryadka (quvvatlagich) — batareyani to'ldirish qurilmasi."),
    ("bluetooth", "Bluetooth — qurilmalar orasida simsiz ma'lumot uzatish texnologiyasi."),
    ("usb", "USB — qurilmalarni ulash porti. Fleşka shu orqali ulanadi."),
    ("fleşka", "Fleshka (USB xotira) — ma'lumotni ko'tarib yurish uchun kichik xotira qurilmasi."),
    ("sim kartasi", "SIM-karta — telefonga raqam va aloqa beradigan kichik karta."),
    ("rozetka", "Rozetka — elektr qurilmalarni ulash uchun devordagi ulagich."),
    ("konditsioner", "Konditsioner — xonani istitadigan yoki sovitadigan qurilma."),
    ("mikroto'lqinli pech", "Mikroto'lqinli pech — ovqatni tez isitadigan qurilma."),

    # ---------- DASTURLASH ----------
    ("dasturlash", "Dasturlash — kompyuterga vazifalarni bajarishni o'rgatish. Kod yozish san'ati."),
    ("algoritm", "Algoritm — masalani yechish uchun ketma-ket qadamlar rejasi."),
    ("kod", "Kod — dasturlash tili qoidalari bilan yozilgan buyruqlar to'plami."),
    ("dasturchi", "Dasturchi — dastur yozadigan mutaxassis. Kompyuterning «tarjimoni»."),
    ("javascript", "JavaScript — brauzerlarda ishlaydigan dasturlash tili. Veb-saytlar jonlanishi shu tilda."),
    ("html", "HTML — veb-sahifa tuzilishini yozadigan belgilash tili."),
    ("css", "CSS — veb-sahifaning ko'rinishini (rang, o'lcham) bezaydigan texnologiya."),
    ("php", "PHP — server tomonda ishlaydigan dasturlash tili. Ko'p saytlar shu tilda yozilgan."),
    ("sql", "SQL — ma'lumotlar bazasi bilan ishlash tili. So'rovlar shu tilda yoziladi."),
    ("java", "Java — kuchli dasturlash tili. Android ilovalar ko'pincha shu tilda yoziladi."),
    ("c++", "C++ — tez ishlaydigan dasturlash tili. O'yinlar va tizimlar shu tilda."),
    ("c#", "C# — Microsoftning dasturlash tili. O'yin va Windows ilovalarida ishlatiladi."),
    ("go", "Go — Google yaratgan sodda va tez dasturlash tili."),
    ("rust", "Rust — xavfsiz va tez dasturlash tili. Zamonaviy tizimlarda ishlatiladi."),
    ("git", "Git — kod versiyalarini boshqarish tizimi. Dasturchilarning eng muhim vositasi."),
    ("github", "GitHub — kodlarni saqlash va hamkorlikda ishlash platformasi."),
    ("framework", "Framework — dasturchiga tayyor asos beradigan vositalar to'plami. Django, Laravel — misollar."),
    ("django", "Django — Python uchun veb-framework. Tez va xavfsiz saytlar yasashga yordam beradi."),
    ("flask", "Flask — Python uchun kichik va sodda veb-framework."),
    ("react", "React — foydalanuvchi interfeysini qurish uchun JavaScript kutubxonasi."),
    ("api so'rovi", "API so'rovi — dastur boshqa dasturga so'rov yuborib javob oladi."),
    ("backend", "Backend — saytning server tomondagi qismi. Ma'lumotlar shu yerda ishlanadi."),
    ("frontend", "Frontend — foydalanuvchi ko'radigan sayt qismi. Dizayn va interfeys."),
    ("fullstack", "Fullstack — ham backend, ham frontend biladigan dasturchi."),
    ("debugging", "Debugging — dasturdagi xatolarni (bug) topish va tuzatish."),
    ("bug", "Bug — dasturdagi xato. «Kompyuterda qurt bor» degan hikoyadan kelib chiqqan."),
    ("kompilyator", "Kompilyator — kodni kompyuter tushunadigan tilga o'giradigan dastur."),
    ("open source", "Ochiq kod (open source) — kodi hammaga ochiq dastur. Python, Linux — misol."),
    ("litsenziya", "Litsenziya — dasturdan foydalanish qoidalari."),
    ("terminal", "Terminal — buyruqlar yozib kompyuterni boshqarish oynasi."),

    # ---------- SUN'IY INTELLEKT ----------
    ("mashina o'rganishi", "Mashina o'rganishi — kompyuterning misollardan o'rganib, xulosa chiqarish usuli."),
    ("chugur o'rganish", "Chuqur o'rganish — ko'p qatlamli neyron tarmoqlar bilan o'rganish. Rasmlar, ovozlarni tushunishda kuchli."),
    ("katta til modeli", "Katta til modeli — milliardlab parametrli, matn yaratadigan AI modeli. ChatGPT mana shunday model."),
    ("generativ ai", "Generativ AI — yangi matn, rasm yoki ovoz yaratadigan sun'iy intellekt."),
    ("chatgpt", "ChatGPT — OpenAI yaratgan mashhur suhbat boti. Savollarga inson kabi javob beradi."),
    ("gpt", "GPT — Generative Pre-trained Transformer. OpenAI model oilasi."),
    ("prompt", "Prompt — AI ga beriladigan ko'rsatma yoki so'rov."),
    ("token", "Token — AI matnni bo'ladigan kichik bo'lak. Model matnni tokenlar bilan ishlaydi."),
    ("obot", "Bot — avtomatik ishlaydigan dastur. Telegram botlari mashhur."),
    ("asistent", "Yordamchi dastur (assistent) — odamga ishlarida yordam beradigan dastur. Masalan, men!"),
    ("taqlid o'rganish", "Reinforcement learning — AIga mukofot va jazo orqali o'rgatish. Robotlar shu usulda o'rganadi."),
    ("natur til", "Tabiiy tilni qayta ishlash (NLP) — kompyuterning inson tilini tushunish texnologiyasi."),
    ("ovozli yordamchi", "Ovozli yordamchi — ovoz buyruqlarini bajaradigan dastur. Siri, Alisa — misol."),
    ("superkompyuter", "Superkompyuter — juda kuchli kompyuter. AI modellarini o'qitishda ishlatiladi."),
    ("neyron", "Neyron — miyadagi nerv hujayrasi. Neyron tarmoq unga o'xshab qurilgan."),
    ("algoritm nima", "Algoritm — muammoni yechish uchun qadamlar ketma-ketligi. Retseptga o'xshaydi."),

    # ---------- INTERNET / TARMOQ ----------
    ("internet tarixi", "Internet — butun dunyo kompyuterlarini bog'laydigan tarmoq. Dastlab harbiy maqsadda yaratilgan."),
    ("veb", "Veb — internetdagi sahifalar tizimi. WWW — butun dunyo vebi."),
    ("veb-sahifa", "Veb-sahifa — brauzerda ochiladigan hujjat. Sayt — bir nechta sahifadan iborat."),
    ("sahifa manzili", "URL — veb-manzil. Masalan, https://example.com."),
    ("http", "HTTP — veb-sahifalarni uzatish protokoli. HTTPS — shifrlangan xavfsiz versiyasi."),
    ("domen", "Domen — sayt nomi, masalan uz.uz. Oson eslab qolish uchun yaratilgan."),
    ("dns", "DNS — domen nomlarini IP-manzilga aylantiradigan tizim."),
    ("ip manzil", "IP-manzil — har bir qurilmaning internetdagi noyob manzili."),
    ("browser", "Brauzer — veb-sahifalarni ko'rish dasturi. Chrome, Firefox, Safari — misol."),
    ("qidiruv tizimi", "Qidiruv tizimi — internetda ma'lumot topish vositasi. Google, Yandex — misol."),
    ("google", "Google — dunyodagi eng mashhur qidiruv tizimi."),
    ("yandex", "Yandex — rus tilidagi mashhur qidiruv tizimi."),
    ("elektron pochta", "E-mail (elektron pochta) — internet orqali xat yuborish tizimi."),
    ("spam", "Spam — kiruvchi keraksiz xatlar."),
    ("virus", "Virus — kompyuterga zarar yetkazadigan dastur. Himoya uchun antivirus kerak."),
    ("antivirus", "Antivirus — kompyuterni viruslardan himoya qiladigan dastur."),
    ("haker", "Haker — tizimlarga kirishda mohir mutaxassis. Yaxshi va yomon hakamlar bor."),
    ("dastur yangilanishi", "Yangilanish (update) — dasturning yangi, tuzatilgan versiyasi."),
    ("bulut", "Bulutli xotira — ma'lumotni internetda saqlash. Google Drive — misol."),
    ("bahodir", "Ijtimoiy tarmoq — odamlar bog'lanadigan platforma. Instagram, Telegram — misol."),
    ("telegram", "Telegram — mashhur messenger ilova. Kanallar va botlar bilan mashhur."),
    ("instagram", "Instagram — surat va video ulashish ijtimoiy tarmog'i."),
    ("youtube", "YouTube — video tomosha qilish va joylash platformasi. Videolar olami!"),
    ("tiktok", "TikTok — qisqa videolar platformasi. Hozir juda mashhur."),
    ("blog", "Blog — odam o'z fikrlarini yozadigan veb-sahifa."),
    ("vlog", "Vlog — blog yuritishning video shakli."),
    ("striming", "Striming — jonli efir orqali video ko'rsatish."),
    ("onlayn", "Onlayn — internetga ulangan holatda. «Onlayn dars» — internet orqali dars."),
    ("oflayn", "Oflayn — internetga ulanmagan holat."),
    ("cloud gaming", "Bulutli o'yinlar — internet orqali kuchli kompyuterda o'ynash."),
    ("botnet", "Botnet — virus bilan boshqariladigan kompyuterlar tarmog'i."),
    ("fishing", "Fishing — soxta saytlar orqali parol o'g'irlash usuli. Ehtiyot bo'ling!"),
]