# -*- coding: utf-8 -*-
"""
MEGA BILIM — G QISM: TA'LIM, KASB, TRANSPORT, TURLI MAVZULAR
"""

KNOWLEDGE = [
    # ---------- TA'LIM / MAKTAB ----------
    ("talim", "Ta'lim — bilim va ko'nikma olish jarayoni. Maktab, kollej, universitet — ta'lim bosqichlari."),
    ("maktab", "Maktab — boshlang'ich va o'rta ta'lim beradigan muassasa. Bilim olamiga eshik!"),
    ("universitet", "Universitet — oliy ta'lim muassasasi. Universitet bitiruvchilari diplom olishadi."),
    ("o'qituvchi", "O'qituvchi — bilim o'rgatuvchi kasb egasi. Eng sharafli kasblardan biri."),
    ("kitob", "Kitob — bilim va hikoyalar manbai. «Kitob — eng yaxshi do'st»."),
    ("darslik", "Darslik — maktabda o'rganiladigan mavzular yozilgan kitob."),
    ("imtihon", "Imtihon — bilimni tekshirish jarayoni. Harakat qilsang, albatta muvaffaq bo'lasan!"),
    ("baholash", "Baholash — o'quvchining bilimini baho bilan o'lchash. 5 — eng yuqori baho!"),
    ("qobiliyat", "Qobiliyat — har kimning tug'ma iqtidori. Uni rivojlantirish kerak."),
    ("ilm", "Ilm — bilim va fan. «Ilm — chiroq, jaholat — zulmat»."),
    ("izlanish", "Tadqiqot — yangi bilim topish uchun izlanish. Olimlar shunday kashfiyot qilishadi."),
    ("kashfiyot", "Kashfiyot — yangi narsa topish yoki ixtiro qilish. Masalan, elektr lampa."),
    ("mashg'ulot", "Mashg'ulot — sport yoki fan bo'yicha muntazam shug'ullanish."),
    ("loy", "Loyiha — reja asosida bajariladigan ish. Dars loyihalari fikrlashni o'rgatadi."),
    ("o'quv yili", "O'quv yili — 1-sentabrdan yozgacha davom etadigan o'qish davri. 1-sentabr — Bilim kuni!"),
    ("qalam", "Qalam — yozish vositasi. Mukammal insho qalamdan boshlanadi."),
    ("daftar", "Daftar — yozuvlar uchun varaqlar to'plami."),
    ("stol", "Stol — o'qish va ishlash uchun mebel. O'quv stoli — ijod maydoni."),
    ("sinf", "Sinf — o'quvchilar guruhi va ular o'qiydigan xona."),
    ("vazifa", "Uy vazifasi — darsda o'tilganni mustahkamlash uchun beriladigan topshiriq."),
    ("o'zlashtirish", "Zabon — o'qish va yozishni bilish. Savodxon inson — erkin inson."),
    ("odob", "Odob — jamiyatda yurish-turish qoidalari. Odobli bola — hamma sevadigan bola."),
    ("mas'uliyat", "Mas'uliyat — o'z ishiga javobgarlikni his qilish. Kattalikning belgisi."),
    ("kelajak", "Kelajak — insonning orzu va maqsadlari amalga oshadigan zamon. Bugun o'qish — ertaga muvaffaqiyat!"),

    # ---------- KASB-HUNARLAR ----------
    ("kash", "Kasb — insonning doimiy ishi. Shifokor, o'qituvchi, dasturchi — kasblar."),
    ("muhandis", "Muhandis — qurilish va texnikani loyihalaydigan mutaxassis."),
    ("arxitektor", "Arxitektor — binolar loyihasini chizadigan mutaxassis."),
    ("avtomehanik", "Avtomexanik — avtomobillarni ta'mirlaydigan mutaxassis."),
    ("tarqatuvchi", "Kuryer — buyurtmalarni yetkazib beruvchi xodim."),
    ("oziq-ovqat texnologi", "Oshpaz — taom tayyorlash ustasi. Shifokor singari, oshpaz ham xalqga xizmat qiladi."),
    ("do'konchilar", "Sotuvchi — mahsulot sotadigan xodim. Xaridor — mehmon!"),
    ("fermer", "Fermer — qishloq xo'jaligi bilan shug'ullanadigan tadbirkor."),
    ("dehqon", "Dehqon — yerda ekin ekib, hosil yetishtiradigan inson. Xalq boqadi."),
    ("cho'pon", "Cho'pon — podani boqadigan chorvador."),
    ("harbiy", "Harbiy — armiyada xizmat qiladigan, Vatanni himoya qiladigan jasur inson."),
    ("uchuvchi", "Uchuvchi (pilot) — samolyotni boshqaradigan mutaxassis."),
    ("shofyor", "Haydovchi — transportni boshqaradigan mutaxassis."),
    ("temiryo'lchi", "Temiryo'lchi — temir yo'l sohasida ishlaydigan xodim."),
    ("quruvchi", "Quruvchi — bino va inshootlar quradigan ishchi."),
    ("duradgor", "Duradgor — yog'ochdan buyumlar yasaydigan usta."),
    ("temirchi", "Temirchi — temirni qizdirib, turli buyumlar yasaydigan usta."),
    ("zargar", "Zargar — oltin va kumushdan zeb-ziynat yasaydigan usta."),
    ("kulol", "Kulol — loydan idish-tovoq yasaydigan usta."),
    ("to'quvchi", "To'quvchi — gazlama to'qish bilan shug'ullanadigan hunarmand."),
    ("kashtachi", "Kashtachi — ip bilan gullar tikadigan mohir hunarmand."),
    ("hunarmand", "Hunarmand — qo'l mehnati bilan buyum yasaydigan usta. Hunar — oltinga teng!"),
    ("santexnik", "Santexnik — suv va isitish tizimlarini ta'mirlaydigan usta."),
    ("elektrik", "Elektrchi — elektr tarmoqlarini o'rnatadigan va ta'mirlaydigan usta."),
    ("buxgalter", "Buxgalter — pul hisobini yuritadigan mutaxassis."),

    # ---------- TRANSPORT ----------
    ("avtomobil", "Avtomobil — yo'lda yuradigan mashina. O'zbekistonda «Damas», «Cobalt» mashhur."),
    ("damas", "Damas — O'zbekistonda ishlab chiqariladigan mashhur kichik avtomobil."),
    ("avtobus", "Avtobus — ko'p odam tashiydigan jamoat transporti."),
    ("metro", "Metro — yer ostidagi tezyurar poyezd tizimi. Toshkent metrosi juda go'zal!"),
    ("poyezd", "Poyezd — relsda yuradigan uzun tarkibli transport."),
    ("samolyot", "Samolyot — havoda uchadigan transport. Tez va qulay."),
    ("vertolyot", "Vertolyot — tik ko'tarilib tushadigan uchish apparati."),
    ("kemacha", "Kema — suvda yuradigan katta transport."),
    ("qayiq", "Qayiq — kichik suv transporti. Eshkak bilan qatnaydi."),
    ("velosiped", "Velosiped — pedal bilan yuradigan ikki g'ildirakli transport."),
    ("motosikl", "Mototsikl — ikki g'ildirakli tez transport."),
    ("skuter", "Skuter — shahar uchun qulay yengil transport."),
    ("taksi", "Taksi — pullik yo'lovchi tashish xizmati."),
    ("samolet bileti", "Chipta — transportda yurish huquqini beradigan hujjat."),
    ("yo'l", "Yo'l — transport harakatlanadigan yo'lak. Yo'l belgilariga e'tibor kerak!"),
    ("svetofor", "Svetofor — yo'l harakatini boshqaradigan chiroq. Qizil — to'xta!"),
    ("piyoda", "Piyoda — yo'lda oyoqda yuradigan odam. Piyodalar yo'lakchasi — xavfsiz joy."),
    ("garaj", "Garaj — avtomobil qo'yiladigan joy."),

    # ---------- TABIAT VA OB-HAVO ----------
    ("ob havo", "Ob-havo — ma'lum vaqt va joydagi atmosfera holati. Quyoshli, bulutli, yomg'irli bo'ladi."),
    ("harorat shkalasi", "Termometr — haroratni o'lchaydigan asbob. Uni ko'chada ham ko'rasiz."),
    ("yosam", "Qurg'oqchilik — uzoq vaqt yomg'ir yog'masdan, yerning qurib qolishi."),
    ("to'fon", "To'fon — kuchli shamol bilan keladigan bo'ron."),
    ("suvayruq'", "Suv toshqini — daryo suvining ko'tarilib, atrofni bosishi."),
    ("yong'in", "Yong'in — nazoratdan chiqqan olov. 101 raqamiga qo'ng'iroq qiling!"),
    ("tabiat", "Tabiat — bizni o'rab turgan hamma narsa: daraxtlar, hayvonlar, daryolar, tog'lar. Uni asrash kerak!"),
    ("ekologiya", "Ekologiya — tabiat va inson o'zaro munosabatini o'rganadigan fan."),
    ("ifloslanish", "Atrof-muhitni ifloslanish — havoning, suvning yoki tuproqning kimyoviy buzilishi."),
    ("qayta ishlash", "Qayta ishlash (recycling) — chiqindidan yangi mahsulot tayyorlash. Tabiatni asraydi!"),

    # ---------- ADABIYOT / KITOBLAR ----------
    ("adabiyot", "Adabiyot — badiiy asarlar (ertak, she'r, roman) sohasi. Millatning ma'naviy xazinasi."),
    ("she'r", "She'r — qofiyali, ritmik badiiy asar. She'r — qalb tilidagi musiqadir."),
    ("roman", "Roman — katta hajmli badiiy asar. "),
    ("hikoya", "Hikoya — qisqa badiiy asar. Bir voqeani bayon qiladi."),
    ("asar qahramoni", "Qahramon — asardagi bosh obraz. Uning taqdiri kitobxonni qiziqtiradi."),
    ("mualif", "Muallif — asarni yozgan shaxs. Kitob muqovasida ko'rsatiladi."),
    ("noshir", "Nashriyot — kitoblarni chop etadigan tashkilot."),
    ("kutubxona", "Kutubxona — kitoblar saqlanadigan va o'qiladigan joy."),
    ("ensiklopediya", "Ensiklopediya — hamma sohaga oid ma'lumotlar lug'ati. Bilim xazinasi!"),
    ("qomus", "Qomus — keng qamrovli bilim to'plami."),
    ("lug'at", "Lug'at — so'zlar va ularning ma'nolari keltirilgan kitob."),
    ("tarjimon", "Tarjimon — bir tildan boshqa tilga o'giradigan mutaxassis."),
    ("ijod", "Ijod — yangi asar yaratish jarayoni. Ijodkor qalbida dunyolar bor!"),

    # ---------- QIZIQ FAKTLAR ----------
    ("qiziq fakt", "Qiziq fakt: aravada, xuddi daryo oqimi kabi — har doim o'rganish oqimini davom eting!"),
    ("suv hayot", "Suv — hayot manbai. Inson tanasining ~70 foizi suvdan iborat."),
    ("havo miqdori", "Havo — ko'rinmas, lekin juda zarur. Bir nafasda ~0,5 litr havo olamiz."),
    ("yulduzlar soni", "Koinotdagi yulduzlar soni — Yerdagi qum donalaridan ham ko'p!"),
    ("inson yuragi", "Inson yuragi bir sutkada ~100 000 marta uradi."),
    ("miya kuchi", "Inson miyasi ~20 vatt energiya sarflaydi. Kichkina lampochkaga teng!"),
    ("burun izi", "Barmoq izi kabi, burun izi ham har odamda noyob."),
    ("arilar", "Asalari bir mavsumda ~2,5 kg asal yig'ishi mumkin. Mehnatkash jonivor!"),
    ("mushuk uyqu", "Mushuklar kuniga ~14 soat uxlaydi. Ularning «uyqu ustalari» ekani ajabmas!"),
    ("tinga", "Quloq suhbatlashganda ham ishlashda davom etadi."),
    ("sayoh", "Charlz Lindberg — 1927-yilda Atlantika okeanini yolg'iz uchib o'tgan birinchi uchuvchi."),
    ("telefon ixtiro", "Telefonni 1876-yilda Aleksandr Bell ixtiro qilgan."),
    ("elektr lampa", "Elektr lampasini Tomas Edison ommalashtirgan."),
    ("velosiped tarixi", "Velosiped 19-asrda mashhur bo'la boshlagan."),
    ("kinoni ixtiro", "Kino 'Lumyer' aka-ukalar tomonidan 1895-yilda ommaga namoyish etilgan."),
    ("televizor", "Televizor — 20-asrning buyuk ixtirosi. Bugun har uyda bor!"),
    ("internet yoshi", "Internet 1990-yillarda butun dunyoga tarqala boshlagan."),
    ("smartfon yoshi", "Birinchi smartfon 1992-yilda chiqarilgan."),
    ("evaziga", "Muvaffaqiyat kaliti — doimiy harakat va o'rganish. Bugun boshlanadi!"),
    ("tabassum", "Tabassum — eng chiroyli til. Barcha tilda tushuniladi!"),
]