# -*- coding: utf-8 -*-
"""
MEGA BILIM — A QISM: DAVLATLAR, SHAHARLAR, O'ZBEKISTON
Bu ro'yxat seed_mega.py orqali ai_knowledge jadvaliga yoziladi.
"""

KNOWLEDGE = [
    # ---------- DAVLATLAR (dunyo) ----------
    ("rossiya", "Rossiya — dunyodagi eng katta davlat, shimolda joylashgan. Poytaxti — Moskva. O'zbekiston bilan qo'shni."),
    ("hindiston", "Hindiston — Osiyodagi aholisi eng ko'p davlatlardan biri. Poytaxti — Nyu-Dehli. Bollar (kino) olami shu yerda!"),
    ("xitoy", "Xitoy — dunyodagi eng ko'p aholili davlat. Poytaxti — Pekin. Zamonaviy texnologiyalar va qadimiy madaniyat mamlakati."),
    ("aqsh", "AQSH — Shimoliy Amerikadagi qudratli davlat. Poytaxti — Vashington. Gollivud aynan shu yerda!"),
    ("yaponiya", "Yaponiya — Osiyodagi texnologik rivojlangan davlat. Poytaxti — Tokio. Anime olamining vatani!"),
    ("koreya", "Janubiy Koreya — Osiyodagi rivojlangan davlat. Poytaxti — Seul. K-drama va K-pop olami shu yerda."),
    ("fransiya", "Fransiya — Yevropadagi go'zal davlat. Poytaxti — Parij. Kino san'ati kashf etilgan joylardan biri."),
    ("italiya", "Italiya — Yevropadagi tarixiy davlat. Poytaxti — Rim. Italiya kinosi — dunyoga mashhur."),
    ("buyuk britaniya", "Buyuk Britaniya — Yevropadagi orol davlat. Poytaxti — London. Bu yerda mashhur kinofilmlar suratga olinadi."),
    ("germaniya", "Germaniya — Yevropaning markazidagi rivojlangan davlat. Poytaxti — Berlin. Ajoyib kinofestivallar o'tkaziladi."),
    ("turkiya", "Turkiya — Osiyo va Yevropa kesishgan joydagi davlat. Poytaxti — Ankara. Turk seriallari butun dunyoda mashhur!"),
    ("misr", "Misr — Afrika va Osiyo kesishgan qadimiy davlat. Poytaxti — Qohira. Piramidalari bilan mashhur."),
    ("g'arbiy yevropa", "Yevropa — Osiyo bilan qo'shni qit'a. Ko'plab rivojlangan davlatlar shu yerda joylashgan."),
    ("qozogiston", "Qozog'iston — Markaziy Osiyodagi davlat, O'zbekistonning shimoliy qo'shnisi. Poytaxti — Ostona."),
    ("qirgiziston", "Qirg'iziston — Markaziy Osiyodagi tog'li davlat. Poytaxti — Bishkek. Issiqko'l shu yerda."),
    ("tojikiston", "Tojikiston — Markaziy Osiyodagi tog'li davlat. Poytaxti — Dushanbe. O'zbekiston bilan qo'shni."),
    ("turkmaniston", "Turkmaniston — Markaziy Osiyodagi davlat. Poytaxti — Ashxobod. Kaspiy dengizi atrofida joylashgan."),
    ("afg'oniston", "Afg'oniston — Osiyodagi tog'li davlat. Poytaxti — Kobul. O'zbekistonning janubiy qo'shnisi."),
    ("eron", "Eron — Osiyodagi tarixiy davlat. Poytaxti — Tehron. Qadimiy madaniyat mamlakati."),
    ("pakiston", "Pokiston — Osiyodagi davlat. Poytaxti — Islomobod. Hindiston bilan qo'shni."),
    ("arabiston", "Saudiya Arabistoni — Arabiston yarim orolidagi davlat. Poytaxti — Ar-Riyod. Hajo va umra shu yerda o'tkaziladi."),
    ("birlashgan arab amirliklari", "BAA — Birlashgan Arab Amirliklari, Osiyodagi rivojlangan davlat. Dubay shahri bilan mashhur."),
    ("isroil", "Isroil — Osiyodagi davlat. Poytaxti — Quddus. Texnologiyalari bilan mashhur."),
    ("gretsiya", "Gretsiya — Yevropadagi qadimiy davlat. Poytaxti — Afina. Olimpiada o'yinlari shu yerda boshlangan."),
    ("ispaniya", "Ispaniya — Yevropadagi davlat. Poytaxti — Madrid. Flamenko raqslari va futboli mashhur."),
    ("portugaliya", "Portugaliya — Yevropadagi davlat. Poytaxti — Lissabon. Buyuk dengizchi sayyohlar mamlakati."),
    ("niderlandiya", "Niderlandiya — Yevropadagi davlat, Gollandiya deb ham ataladi. Poytaxti — Amsterdam."),
    ("belgiya", "Belgiya — Yevropadagi kichik davlat. Poytaxti — Bryussel. Yevropa Ittifoqi markazi shu yerda."),
    ("shveytsariya", "Shveytsariya — Yevropadagi tog'li davlat. Poytaxti — Bern. Banklari va soati mashhur."),
    ("avstriya", "Avstriya — Yevropadagi davlat. Poytaxti — Vena. Ajoyib musiqa mamlakati."),
    ("shvetsiya", "Shvetsiya — Shimoliy Yevropadagi davlat. Poytaxti — Stokgolm. Nobel mukofoti shu yerda beriladi."),
    ("norvegiya", "Norvegiya — Shimoliy Yevropadagi davlat. Poytaxti — Oslo. Fiordlari bilan mashhur."),
    ("daniya", "Daniya — Shimoliy Yevropadagi davlat. Poytaxti — Kopengagen."),
    ("finlyandiya", "Finlyandiya — Shimoliy Yevropadagi davlat. Poytaxti — Xelsinki. Saunalar vatani."),
    ("polsha", "Polsha — Yevropadagi davlat. Poytaxti — Varshava."),
    ("chexiya", "Chexiya — Yevropadagi davlat. Poytaxti — Praga. Go'zal me'morchiligi bilan mashhur."),
    ("ruminiya", "Ruminiya — Yevropadagi davlat. Poytaxti — Buxarest."),
    ("bolgariya", "Bolgariya — Yevropadagi davlat. Poytaxti — Sofiya."),
    ("serbiya", "Serbiya — Bolqon yarim orolidagi davlat. Poytaxti — Belgrad."),
    ("ukraina", "Ukraina — Sharqiy Yevropadagi davlat. Poytaxti — Kiyev."),
    ("belarus", "Belarus — Sharqiy Yevropadagi davlat. Poytaxti — Minsk."),
    ("gruziya", "Gruziya — Kavkazdagi davlat. Poytaxti — Tbilisi. Sharobchilik mamlakati."),
    ("armaniston", "Armaniston — Kavkazdagi davlat. Poytaxti — Yerevan."),
    ("ozarbayjon", "Ozarbayjon — Kavkazdagi davlat. Poytaxti — Boku. Neft qazib olishda mashhur."),
    ("kanada", "Kanada — Shimoliy Amerikadagi rivojlangan davlat. Poytaxti — Ottava."),
    ("meksika", "Meksika — Shimoliy Amerikadagi davlat. Poytaxti — Mexiko shahri. Qadimiy sivilizatsiyalar makoni."),
    ("braziliya", "Braziliya — Janubiy Amerikadagi eng katta davlat. Poytaxti — Braziliya. Karnaval va futbol mamlakati!"),
    ("argentina", "Argentina — Janubiy Amerikadagi davlat. Poytaxti — Buenos-Ayres. Tango raqsi shu yerda tug'ilgan."),
    ("chili", "Chili — Janubiy Amerikadagi davlat. Poytaxti — Santyago."),
    ("peru", "Peru — Janubiy Amerikadagi davlat. Poytaxti — Lima. Machu-Pikchu shu yerda."),
    ("venesuela", "Venesuela — Janubiy Amerikadagi davlat. Poytaxti — Karakas."),
    ("kolumbiya", "Kolumbiya — Janubiy Amerikadagi davlat. Poytaxti — Bogota. Kofesi mashhur."),
    ("australiya", "Avstraliya — qit'a bo'lgan yagona davlat. Poytaxti — Kanberra. Kenguru va koala shu yerda!"),
    ("yangi zelandiya", "Yangi Zelandiya — Tinch okeandagi davlat. Poytaxti — Vellington. Tabiati misli ko'rilmagan go'zal."),
    ("indoneziya", "Indoneziya — Osiyodagi orollar davlati. Poytaxti — Jakarta. Bali oroli bilan mashhur."),
    ("tailand", "Tailand — Osiyodagi davlat. Poytaxti — Bangkok. Plajlari bilan mashhur."),
    ("vietnam", "Vyetnam — Osiyodagi davlat. Poytaxti — Xanoy."),
    ("malayziya", "Malayziya — Osiyodagi davlat. Poytaxti — Kuala-Lumpur."),
    ("singapur", "Singapur — Osiyodagi kichik, ammo juda rivojlangan davlat. Kellang shahri bilan mashhur."),
    ("filippin", "Filippin — Osiyodagi orollar davlati. Poytaxti — Manila."),
    ("birma", "Myanma (Birma) — Osiyodagi davlat. Poytaxti — Naypyidov."),
    ("niqrobiya", "Nigeriya — Afrikadagi aholisi eng ko'p davlat. Poytaxti — Abuja."),
    ("efiopiya", "Efiopiya — Afrikadagi davlat. Poytaxti — Addis-Abeba."),
    ("keniya", "Keniya — Afrikadagi davlat. Poytaxti — Nayrobi. Safarilar mamlakati."),
    ("jazo'r", "Jazoir — Afrikadagi davlat. Poytaxti — Jazoir shahri. Sahroi Kabirning katta qismi shu yerda."),
    ("marokash", "Marokash — Afrikadagi davlat. Poytaxti — Rabot."),
    ("tunis", "Tunis — Afrikadagi davlat. Poytaxti — Tunis shahri."),
    ("janubiy afrika", "Janubiy Afrika Respublikasi — Afrikaning janubidagi davlat. Poytaxtlari — Pretoriya, Keyptaun."),
    ("mavrikiy", "Mavrikiy — Hind okeanidagi orol davlat. Sayyohlar sevadigan joy."),

    # ---------- DUNYO SHAHARLARI ----------
    ("london", "London — Buyuk Britaniyaning poytaxti. Big Ben va Temza daryosi bilan mashhur."),
    ("parij", "Parij — Fransiyaning poytaxti, «nurlar shahri». Eyfel minorasi shu yerda joylashgan."),
    ("nyu-york", "Nyu-York — AQSHning eng katta shahri. Statuya Ozodlik, «katta olma» deb ataladi."),
    ("tokio", "Tokio — Yaponiyaning poytaxti, dunyodagi eng katta metropoliyalardan biri."),
    ("seul", "Seul — Janubiy Koreyaning poytaxti. Zamonaviy texnologiyalar shahri."),
    ("pekin", "Pekin — Xitoyning poytaxti. Qadimiy va zamonaviy uyg'unlashgan shahar."),
    ("moskva", "Moskva — Rossiyaning poytaxti. Qizil maydon va Kreml shu yerda."),
    ("dubay", "Dubay — BAA'dagi shahar. Dunyodagi eng baland bino — Burj Xalifa shu yerda!"),
    ("istanbul", "Istanbul — Turkiyadagi eng katta shahar. Ikki qit'ani bog'laydi: Osiyo va Yevropa."),
    ("berlin", "Berlin — Germaniyaning poytaxti. Berlindagi devor tarixi bilan mashhur."),
    ("rim", "Rim — Italiyaning poytaxti, «abadiy shahar». Kolizey shu yerda."),
    ("madrid", "Madrid — Ispaniyaning poytaxti. Futbol va muzeylari bilan mashhur."),
    ("barcelona", "Barselona — Ispaniyadagi go'zal shahar. Arxitektura asarlari bilan mashhur."),
    ("vena", "Vena — Avstriyaning poytaxti, musiqachilar shahri."),
    ("praga", "Praga — Chexiyaning poytaxti. Qadimiy qal'alari bilan mashhur."),
    ("amsterdam", "Amsterdam — Niderlandiyaning poytaxti. Kanallari bilan mashhur."),
    ("stokgolm", "Stokgolm — Shvetsiyaning poytaxti. Ko'p orollardan iborat shahar."),
    ("kopengagen", "Kopengagen — Daniyaning poytaxti."),
    ("oslo", "Oslo — Norvegiyaning poytaxti."),
    ("xelsinki", "Xelsinki — Finlyandiyaning poytaxti."),
    ("varshava", "Varshava — Polshaning poytaxti."),
    ("kiyev", "Kiyev — Ukrainaning poytaxti."),
    ("minsk", "Minsk — Belarusning poytaxti."),
    ("boku", "Boku — Ozarbayjonning poytaxti. Kaspiy dengizi sohilida joylashgan."),
    ("tbilisi", "Tbilisi — Gruziyaning poytaxti. Go'zal tog'lar orasida."),
    ("erevan", "Yerevan — Armanistonning poytaxti. Aravot tog'ining etagida."),
    ("qohira", "Qohira — Misrning poytaxti. Piramidalarga yaqin joyda."),
    ("keyptaun", "Keyptaun — Janubiy Afrikadagi go'zal shahar. Table Mountain bilan mashhur."),
    ("rio", "Rio-de-Janeyro — Braziliyadagi shahar. Karnavali va Xrist figurasi bilan mashhur."),
    ("los-angeles", "Los-Anjeles — AQSHdagi shahar. Gollivud va kinostudiylar shu yerda!"),
    ("sietl", "Sietl — AQSHdagi shahar. Qahva madaniyati bilan mashhur."),

    # ---------- O'ZBEKISTON ----------
    ("andijon", "Andijon — O'zbekistonning Farg'ona vodiysidagi shahri. Bobur shu yerda tug'ilgan."),
    ("namangan", "Namangan — O'zbekistonning Farg'ona vodiysidagi shahri. «Yoshlar shahri» deb ataladi."),
    ("farg'ona", "Farg'ona — O'zbekistonning sharqidagi shahar, vodiyni markazi."),
    ("qo'qon", "Qo'qon — Farg'ona vodiysidagi tarixiy shahar. Qo'qon xonligi poytaxti bo'lgan."),
    ("nukus", "Nukus — Qoraqalpog'istonning poytaxti. Savitskiy muzeyi shu yerda joylashgan."),
    ("urganch", "Urganch — Xorazm viloyatining markazi."),
    ("termiz", "Termiz — O'zbekistonning janubidagi shahar, Afg'oniston bilan chegaradosh."),
    ("jizzax", "Jizzax — O'zbekistonning markaziy shahri."),
    ("guliston", "Guliston — Sirdaryo viloyatining markazi."),
    ("qarshi", "Qarshi — Qashqadaryo viloyatining markazi."),
    ("denov", "Denov — Surxondaryo viloyatidagi shahar."),
    ("navoiy", "Navoiy — O'zbekistondagi zamonaviy shahar, sanoat markazi."),
    ("chirchiq", "Chirchiq — Toshkent viloyatidagi shahar, kimyo sanoati bilan mashhur."),
    ("angren", "Angren — Toshkent viloyatidagi konchilar shahri."),
    ("olmaliq", "Olmaliq — Toshkent viloyatidagi shahar, mis konlari bilan mashhur."),
    ("buxoro viloyati", "Buxoro — O'zbekistonning qadimiy shahri, Buyuk ipak yo'lidagi markazlardan biri."),
    ("xiva shahri", "Xiva — Xorazmdagi qadimiy shahar, Ichan-qal'a — YuNESKO merosi."),
    ("shahrisabz", "Shahrisabz — Amir Temur tug'ilgan shahar. Oqsaroy shu yerda."),
    ("zomin", "Zomin — Jizzax viloyatidagi tog'li shaharcha, sanatoriyalari bilan mashhur."),
    ("chortoq", "Chortoq — Namangan viloyatidagi shaharcha, mineral suvlari bilan mashhur."),
    ("sirdaryo", "Sirdaryo — O'zbekistondagi daryo va viloyat. Uzunligi bo'yicha O'rta Osiyoda yetakchi."),
    ("amudaryo", "Amudaryo — O'zbekistonning janubidagi buyuk daryo. Orolga quyilgan."),
    ("zarafshon", "Zarafshon — O'zbekistondagi daryo, «oltin sochuvchi» degan ma'noni anglatadi."),
    ("qizilqum", "Qizilqum — O'zbekistondagi katta cho'l. «Qizil qum» degani."),
    ("qoraqalpog'iston", "Qoraqalpog'iston — O'zbekiston tarkibidagi avtonom respublika. Orol dengizi shu yerda."),
    ("orol dengizi", "Orol dengizi — O'zbekiston va Qozog'iston oralig'idagi berk ko'l. Yaqin tarixda kichraygani bilan mashhur."),
    ("chortoq suvi", "Chortoq mineral suvi — Namangandagi shifo buloqlaridan olinadi."),
    ("registon", "Registon — Samarqanddagi mashhur maydon, uchta madrasa bilan o'ralgan."),
    ("ipak yo'li", "Buyuk ipak yo'li — qadimda Xitoydan Yevropagacha bo'lgan savdo yo'li. O'zbekiston uning markazida edi."),

    # ---------- GEOGRAFIYA QO'SHIMCHA ----------
    ("qit'a", "Qit'a — Yerning katta quruqlik massivi. Dunyoda 6 qit'a bor: Osiyo, Afrika, Yevropa, Amerika, Avstraliya va Antarktida."),
    ("poytaxt nima", "Poytaxt — davlatning boshqaruv markazi bo'lgan shahri."),
    ("chegara", "Chegara — ikki davlat orasidagi chegara chizig'i."),
    ("markaziy osiyo", "Markaziy Osiyo — O'zbekiston, Qozog'iston, Qirg'iziston, Tojikiston, Turkmaniston joylashgan mintaqa."),
    ("toshkent shahri", "Toshkent — O'zbekistonning poytaxti va eng katta shahri. «Toshkent — shahar» degani."),
]